# Generated by Django 5.2.5 on 2025-08-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsData',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.JSONField()),
                ('city', models.JSONField()),
                ('coordinates', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airports_data',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='AircraftsData',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('model', models.JSONField()),
                ('range', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'aircrafts_data',
                'unique_together': {('aircraft_code', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=6)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flightapp.aircraftsdata')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='flightapp.airportsdata')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='flightapp.airportsdata')),
            ],
            options={
                'db_table': 'flights',
                'unique_together': {('flight_no', 'scheduled_departure')},
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField()),
                ('contact_data', models.JSONField(blank=True, null=True)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.bookings')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flights')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.tickets')),
            ],
            options={
                'db_table': 'ticket_flights',
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=4)),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=10)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.aircraftsdata')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('aircraft_code', 'seat_no')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField()),
                ('boarding_no', models.IntegerField()),
                ('seat_no', models.CharField(max_length=4)),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.ticketflights')),
            ],
            options={
                'db_table': 'boarding_passes',
                'unique_together': {('flight_id', 'boarding_no')},
            },
        ),
    ]
