# Generated by Django 5.2.5 on 2025-08-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingpasses',
            name='ticket_no',
            field=models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, to='flightapp.ticketflights'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='aircraft_code',
            field=models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.deletion.PROTECT, to='flightapp.aircraftsdata'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='arrival_airport',
            field=models.ForeignKey(db_column='arrival_airport', on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='flightapp.airportsdata'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_airport',
            field=models.ForeignKey(db_column='departure_airport', on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='flightapp.airportsdata'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='aircraft_code',
            field=models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.deletion.CASCADE, to='flightapp.aircraftsdata'),
        ),
        migrations.AlterField(
            model_name='ticketflights',
            name='flight_id',
            field=models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='flightapp.flights'),
        ),
        migrations.AlterField(
            model_name='ticketflights',
            name='ticket_no',
            field=models.ForeignKey(db_column='ticket_no', on_delete=django.db.models.deletion.CASCADE, to='flightapp.tickets'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='book_ref',
            field=models.ForeignKey(db_column='book_ref', on_delete=django.db.models.deletion.CASCADE, to='flightapp.bookings'),
        ),
        migrations.AddIndex(
            model_name='flights',
            index=models.Index(fields=['departure_airport', 'scheduled_departure'], name='flights_departu_6d6aa6_idx'),
        ),
    ]
