# Generated by Django 5.2.5 on 2025-09-03 11:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_alter_boardingpasses_ticket_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsdata',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
