# Generated by Django 5.2.5 on 2025-09-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_alter_airportsdata_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportsdata',
            options={'managed': False},
        ),
    ]
