# Generated by Django 5.2.5 on 2025-09-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_airportsdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportsdata',
            options={},
        ),
    ]
