# Generated by Django 5.2.5 on 2025-09-04 07:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_alter_airportsdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsdata',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
